version: '3'

services:
  db:
    container_name: mysql
    image: mysql
    volumes:
      - $PWD/data:/var/lib/mysql
      - $PWD/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps
    ports:
      - "3306"
    networks:
      - my_net

  ps:
    container_name: ps-web
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db
    ports:
      - 18888:443
      - 8080:80
      - 443:443
    environment:
      DB_SERVER: db
      DB_USER: ps
      DB_PASSWD: ps
      DEV_MODE: 1
      DB_NAME: ps
      #PS_FOLDER_ADMIN: admin1 # localhost:8080/admin1 tu znajdziemy panel admina
      #PS_FOLDER_INSTALL: install1 # jak wchodzimy instalować, to na localhost:8080/install1
    networks:
      - my_net

networks:
  my_net:


# Przy instalacji wpisujcie:
# Nazwa sklepu Kamieniary
# Dzialnosc Inne
# Kraj Polska
# SSL Nie, oskar mowi ze bedzie trzeba niby to ssl zrobic ale nw wtedy cos sie jebie
# Imie: Gogacz
# Nazwisko: Gogaczow
# adres email: xyz@w.pl - sie kurwa jebnalem
# Haslo: KochamPreste123!

# Przy bazce:
# u gory db, na reszcie ps

# jesli w wyszukiwarce znajdziecie kamien mocy to jest super dziala

# odpalacie za pomoca docker-compose up -d
# zamykacie za pomoca docker-compose down
