<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.cdc.client.distribution_api' shared service.

return $this->services['mbo.cdc.client.distribution_api'] = new \PrestaShop\Module\Mbo\Distribution\Client(${($_ = isset($this->services['mbo.distribution_api.client.http']) ? $this->services['mbo.distribution_api.client.http'] : $this->load('getMbo_DistributionApi_Client_HttpService.php')) && false ?: '_'}, ${($_ = isset($this->services['mbo.doctrine.cache.provider']) ? $this->services['mbo.doctrine.cache.provider'] : $this->load('getMbo_Doctrine_Cache_ProviderService.php')) && false ?: '_'});
