<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ps_checkout.tactician.bus' shared service.

return $this->services['ps_checkout.tactician.bus'] = ${($_ = isset($this->services['ps_checkout.tactician.bus.factory']) ? $this->services['ps_checkout.tactician.bus.factory'] : $this->load('getPsCheckout_Tactician_Bus_FactoryService.php')) && false ?: '_'}->create();
