<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.query.handler.paypal.order.get_paypal_order_for_checkout_completed' shared service.

return $this->services['ps_checkout.query.handler.paypal.order.get_paypal_order_for_checkout_completed'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\Order\QueryHandler\GetPayPalOrderForCheckoutCompletedQueryHandler(${($_ = isset($this->services['ps_checkout.cache.paypal.order']) ? $this->services['ps_checkout.cache.paypal.order'] : $this->load('getPsCheckout_Cache_Paypal_OrderService.php')) && false ?: '_'});
