<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.paypal.provider.client_token' shared service.

return $this->services['ps_checkout.paypal.provider.client_token'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\PayPalClientTokenProvider(${($_ = isset($this->services['ps_checkout.repository.pscheckoutcart']) ? $this->services['ps_checkout.repository.pscheckoutcart'] : $this->load('getPsCheckout_Repository_PscheckoutcartService.php')) && false ?: '_'});
