<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.addons.user.credentials_encryptor' shared service.

return $this->services['mbo.addons.user.credentials_encryptor'] = new \PrestaShop\Module\Mbo\Addons\User\CredentialsEncryptor();
