<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'ps_checkout.event.dispatcher.symfony' shared service.

return $this->services['ps_checkout.event.dispatcher.symfony'] = ${($_ = isset($this->services['ps_checkout.event.dispatcher.factory']) ? $this->services['ps_checkout.event.dispatcher.factory'] : $this->load('getPsCheckout_Event_Dispatcher_FactoryService.php')) && false ?: '_'}->create([0 => ${($_ = isset($this->services['ps_checkout.event.subscriber.checkout']) ? $this->services['ps_checkout.event.subscriber.checkout'] : $this->load('getPsCheckout_Event_Subscriber_CheckoutService.php')) && false ?: '_'}, 1 => ${($_ = isset($this->services['ps_checkout.event.subscriber.order']) ? $this->services['ps_checkout.event.subscriber.order'] : $this->load('getPsCheckout_Event_Subscriber_OrderService.php')) && false ?: '_'}, 2 => ${($_ = isset($this->services['ps_checkout.event.subscriber.paypal.order']) ? $this->services['ps_checkout.event.subscriber.paypal.order'] : $this->load('getPsCheckout_Event_Subscriber_Paypal_OrderService.php')) && false ?: '_'}, 3 => ${($_ = isset($this->services['ps_checkout.event.subscriber.paypal.capture']) ? $this->services['ps_checkout.event.subscriber.paypal.capture'] : $this->load('getPsCheckout_Event_Subscriber_Paypal_CaptureService.php')) && false ?: '_'}]);
