<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.validator.batch_configuration' shared service.

return $this->services['ps_checkout.validator.batch_configuration'] = new \PrestaShop\Module\PrestashopCheckout\Validator\BatchConfigurationValidator();
