<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.command.handler.order.add_order_payment' shared service.

return $this->services['ps_checkout.command.handler.order.add_order_payment'] = new \PrestaShop\Module\PrestashopCheckout\Order\CommandHandler\AddOrderPaymentCommandHandler(${($_ = isset($this->services['ps_checkout.event.dispatcher']) ? $this->services['ps_checkout.event.dispatcher'] : $this->load('getPsCheckout_Event_DispatcherService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.funding_source.translation']) ? $this->services['ps_checkout.funding_source.translation'] : $this->load('getPsCheckout_FundingSource_TranslationService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.paypal.configuration']) ? $this->services['ps_checkout.paypal.configuration'] : $this->load('getPsCheckout_Paypal_ConfigurationService.php')) && false ?: '_'});
