<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.distribution_api.client.http' shared service.

return $this->services['mbo.distribution_api.client.http'] = new \GuzzleHttp\Client(['base_url' => $this->getEnv('DISTRIBUTION_API_URL'), 'timeout' => '7200', 'headers' => ['Accept' => 'application/json'], 'CURLOPT_FORBID_REUSE' => true, 'CURLOPT_FRESH_CONNECT' => true]);
