<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'mbo.controller.security' shared service.

return $this->services['mbo.controller.security'] = new \PrestaShop\Module\Mbo\Controller\Admin\SecurityController();
