<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.paypal.builder.view_order_summary' shared service.

return $this->services['ps_checkout.paypal.builder.view_order_summary'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\Order\PayPalOrderSummaryViewBuilder(${($_ = isset($this->services['ps_checkout.repository.pscheckoutcart']) ? $this->services['ps_checkout.repository.pscheckoutcart'] : $this->load('getPsCheckout_Repository_PscheckoutcartService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.paypal.provider.order']) ? $this->services['ps_checkout.paypal.provider.order'] : $this->load('getPsCheckout_Paypal_Provider_OrderService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.prestashop.router']) ? $this->services['ps_checkout.prestashop.router'] : ($this->services['ps_checkout.prestashop.router'] = new \PrestaShop\Module\PrestashopCheckout\Routing\Router())) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.paypal.order.translations']) ? $this->services['ps_checkout.paypal.order.translations'] : $this->load('getPsCheckout_Paypal_Order_TranslationsService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.context.shop']) ? $this->services['ps_checkout.context.shop'] : ($this->services['ps_checkout.context.shop'] = new \PrestaShop\Module\PrestashopCheckout\ShopContext())) && false ?: '_'});
