<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.webhook.handler' shared service.

return $this->services['ps_checkout.webhook.handler'] = new \PrestaShop\Module\PrestashopCheckout\Webhook\WebhookHandler(${($_ = isset($this->services['ps_checkout.webhook.service.secret_token']) ? $this->services['ps_checkout.webhook.service.secret_token'] : $this->load('getPsCheckout_Webhook_Service_SecretTokenService.php')) && false ?: '_'}, [0 => ${($_ = isset($this->services['ps_checkout.webhook.handler.event.configuration_updated']) ? $this->services['ps_checkout.webhook.handler.event.configuration_updated'] : $this->load('getPsCheckout_Webhook_Handler_Event_ConfigurationUpdatedService.php')) && false ?: '_'}]);
