<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ps_checkout.event.subscriber.paypal.capture' shared service.

return $this->services['ps_checkout.event.subscriber.paypal.capture'] = new \PrestaShop\Module\PrestashopCheckout\PayPal\Payment\Capture\EventSubscriber\PayPalCaptureEventSubscriber(${($_ = isset($this->services['ps_checkout.module']) ? $this->services['ps_checkout.module'] : $this->load('getPsCheckout_ModuleService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.order.service.check_order_amount']) ? $this->services['ps_checkout.order.service.check_order_amount'] : ($this->services['ps_checkout.order.service.check_order_amount'] = new \PrestaShop\Module\PrestashopCheckout\Order\Service\CheckOrderAmount())) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.cache.paypal.capture']) ? $this->services['ps_checkout.cache.paypal.capture'] : $this->load('getPsCheckout_Cache_Paypal_CaptureService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.cache.paypal.order']) ? $this->services['ps_checkout.cache.paypal.order'] : $this->load('getPsCheckout_Cache_Paypal_OrderService.php')) && false ?: '_'}, ${($_ = isset($this->services['ps_checkout.order.state.service.order_state_mapper']) ? $this->services['ps_checkout.order.state.service.order_state_mapper'] : $this->load('getPsCheckout_Order_State_Service_OrderStateMapperService.php')) && false ?: '_'});
