<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYj57doh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYj57doh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYj57doh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYj57doh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYj57doh\appProdProjectContainer([
    'container.build_hash' => 'Yj57doh',
    'container.build_id' => '1610c59b',
    'container.build_time' => 1701721717,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYj57doh');
