<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtbvevt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtbvevt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUtbvevt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUtbvevt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUtbvevt\appProdProjectContainer([
    'container.build_hash' => 'Utbvevt',
    'container.build_id' => '3abc96b4',
    'container.build_time' => 1701723734,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtbvevt');
