<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2erse32\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2erse32/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2erse32.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2erse32\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2erse32\appProdProjectContainer([
    'container.build_hash' => '2erse32',
    'container.build_id' => '7cb68020',
    'container.build_time' => 1698411151,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2erse32');
